language: node_js

node_js:
  - stable

before_script:
  - git config --global user.email "garvit.singh4@gmail.com"
  - git config --global user.name "gsingh04"

script:
  - cd source/services/limitreport/ && npm run test

notifications:
  email:
    recipients:
      - garvit.singh4@gmail.com
    on_success: always
    on_failure: always
