language: node_js

node_js:
  - 8.10

jobs:  
  include:
    - stage: test                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: cd deployment && chmod +x ./run-unit-tests.sh && ./run-unit-tests.sh
    - stage: build
      name: "Build Solution Artifacts"
      script: chmod +x ./build-s3-dist.sh && ./build-s3-dist.sh my_bucket my_bucket vX.Y

notifications:
  email:
    recipients:
      - garvit.singh4@gmail.com
    on_success: always
    on_failure: always
